#!/usr/bin/env bash
# =====================================================================
# Grafana Mimir App - Nginx Home Assistant Ingress
# =====================================================================

mimir_configure_nginx() {
    local nginx_auth_map
    local proxy_listen_block

    mkdir -p "$(dirname "${MIMIR_NGINX_CONF}")"

    if is_true "${AUTH_TOKEN_ENABLED}"; then
        basic_auth_base64="$(echo -n "${AUTH_USER}:${AUTH_TOKEN}" | base64)"
        nginx_auth_map=$(cat <<EOF_NGINX_AUTH
map \$http_authorization \$mimir_auth_ok {
    default 0;
    "Basic ${basic_auth_base64}" 1;
}
EOF_NGINX_AUTH
)
    else
        nginx_auth_map=$(cat <<'EOF_NGINX_AUTH_OFF'
map $http_authorization $mimir_auth_ok {
    default 1;
}
EOF_NGINX_AUTH_OFF
)
    fi

    proxy_listen_block=""
    if is_true "${TLS_ENABLED}"; then
        proxy_listen_block="    add_header X-Frame-Options \"SAMEORIGIN\" always;
    add_header X-Content-Type-Options \"nosniff\" always;
    add_header X-XSS-Protection \"1; mode=block\" always;
    add_header Referrer-Policy \"strict-origin-when-cross-origin\" always;

    listen ${HTTP_PORT} default_server ssl;
    listen [::]:${HTTP_PORT} default_server ssl;
    server_name _;

    ssl_certificate ${CERT_FILE};
    ssl_certificate_key ${KEY_FILE};"
    else
    proxy_listen_block="    listen ${HTTP_PORT} default_server;
    listen [::]:${HTTP_PORT} default_server;
    server_name _;"
    fi


    cat > "${MIMIR_NGINX_CONF}" <<EOF_NGINX
# =====================================================================
# SpiritScorp Mimir - Nginx Ingress Proxy Configuration
# Generated by run.sh
# =====================================================================

${nginx_auth_map}

# ---------------------------------------------------------------------
# Server 1: Home Assistant Ingress (Port ${DEFAULT_INGRESS_PORT})
# Protected natively by Home Assistant Supervisor authentication.
# Serves Ingress UI assets and proxies internal UI requests to Mimir.
# ---------------------------------------------------------------------
server {
    listen ${DEFAULT_INGRESS_PORT} default_server;
    listen [::]:${DEFAULT_INGRESS_PORT} default_server;
    server_name _;

    root /var/www/mimir-ui;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Ingress UI Root
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Proxy to Mimir internal engine for UI views (/services, /config, /ready, etc.)
    location /proxy/mimir/ {
        proxy_pass http://127.0.0.1:${MIMIR_PORT}/;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Ingress-Path \$http_x_ingress_path;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Streaming and buffer optimization for large Prometheus remote-write pushes
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;

        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
    }

    # Internal health check for Nginx
    location /healthz {
        access_log off;
        return 200 "OK\n";
    }
}


# ---------------------------------------------------------------------
# Server 2: Public Mimir API & Prometheus Remote-Write (Port ${HTTP_PORT})
# Accessible to external clients (Prometheus, Grafana, IoT devices).
# Protected by Basic Authentication if enabled in App options.
# ---------------------------------------------------------------------
server {

${proxy_listen_block}

    client_max_body_size 50M;

    location / {
        if (\$mimir_auth_ok = 0) {
            return 401;
        }

        proxy_pass http://127.0.0.1:${MIMIR_PORT};
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Streaming and buffer optimization for large Prometheus remote-write pushes
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_connect_timeout 10s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
EOF_NGINX

    if ! nginx -t; then
        log_error "Generated nginx configuration is invalid."
        exit 1
    fi

    log_info "Generated nginx configuration validated successfully."
}

