name: "Build & Publish Home Assistant App"

on:
  release:
    types: ["published"]
  workflow_dispatch:
    inputs:
      target:
        description: "App target folder to build (e.g. mimir)"
        required: true
        default: "mimir"
      version:
        description: "Version to build and publish (e.g. 1.0.0)"
        required: true
        default: "1.0.0"

jobs:
  build:
    name: "Build Multi-Arch App (home-assistant/builder)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Verify Multi-Arch Docker Build"
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --target mimir \
            --image "mimir-{arch}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"
