name: "CI & App Validation"

on:
  push:
    branches: ["main" , "fix/*"]
  pull_request:
    branches: ["main"]

env:
  ARCHITECTURES: '["amd64", "aarch64"]'

jobs:
  resolve-targets:
    name: "Discover App Targets"
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Find all app folders"
        id: set-targets
        run: |
          TARGETS_JSON=$(find . -maxdepth 2 -name "Dockerfile" -exec dirname {} \; | sed 's|^\./||' | jq -R . | jq -s -c .)
          echo "targets=${TARGETS_JSON}" >> $GITHUB_OUTPUT

  test_mimir:
    name: "Validate Mimir App & Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7

      - name: "Set up Python & ShellCheck"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: "Install yamllint & pyyaml"
        run: pip install pyyaml yamllint

      - name: "Run ShellCheck on test scripts"
        run: |
          find . -type f -name "*.sh" -exec shellcheck -x {} +

      - name: "Run App Test Suite"
        run: |
          chmod +x mimir/tests/validate.sh
          mimir/tests/validate.sh

  init:
    name: "Initialize Build Matrix for ${{ matrix.target }}"
    needs: [resolve-targets, test_mimir]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.resolve-targets.outputs.targets) }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Get build matrix"
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.09.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name:  "ha-spiritscorp-${{ matrix.target }}"

  verify_build:
    name: "Verify ${{ matrix.arch }} Docker Build (${{ matrix.target }})"
    needs: [resolve-targets, init]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read # To check out the code
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push built images to GitHub Container Registry
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Build image (dry-run)"
        uses: home-assistant/builder/actions/build-image@2026.09.0
        with:
          arch: ${{ matrix.arch }}
          context: ${{ matrix.target }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          push: "false"
          version: ${{ github.ref_name }}