name: "CI & App Validation"

on:
  push:
    branches: ["main" , "fix/*"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: "Validate Mimir App & Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7

      - name: "Set up Python & ShellCheck"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: "Install yamllint & pyyaml"
        run: pip install pyyaml yamllint

      - name: "Run ShellCheck on test scripts"
        run: |
          find . -type f -name "*.sh" -exec shellcheck -x {} +

      - name: "Run App Test Suite"
        run: |
          chmod +x mimir/tests/validate.sh
          mimir/tests/validate.sh
          
  build:
    name: "Verify Multi-Arch Docker Build"
    permissions:
      contents: read
    uses: home-assistant/actions/.github/workflows/builder.yaml@master
    with:
      args: |
        --test \
        --amd64 \
        --aarch64 \
        --target ${{ inputs.target || 'mimir' }} \
        --version ${{ inputs.version || github.ref_name }} \        
        --image "ha-spiritscorp-${{ inputs.target || 'mimir' }}-{arch}" \
        --docker-hub "ghcr.io/${{ github.repository_owner }}"
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}